--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Alternatively, you can contact us on the HappinessMP Discord."
    name: "Support Chat"
    url: "https://discord.com/invite/s5gwNWq"
